name: Build and Testing Rust Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout branch in CI
      uses: actions/checkout@v3

    - name: Run tests
      run: cargo test --release --verbose

    
  build:
    strategy:
      matrix:
        os: [ macos, ubuntu ]

    needs: [test]
    runs-on: ${{matrix.os}}-latest
    steps:
      - name: Checkout branch in CI
        uses: actions/checkout@v3

      - name: Install dependencies for OpenCL 
        if: ${{ matrix.os == 'Ubuntu' }}
        run: |
          sudo apt install -y ocl-icd-libopencl1 ocl-icd-opencl-dev pocl-opencl-icd clinfo
      
      - name: Show OpenCL Device info 
        if: ${{ matrix.os == 'Ubuntu' }}
        run: clinfo --human

      - name: Build
        run: cargo build --release --verbose
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_build_bin
          path: target/release/path_walker