name: Build and Testing Rust Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install OpenCL dependencies
        run: sudo apt install -y ocl-icd-libopencl1 ocl-icd-opencl-dev pocl-opencl-icd clinfo
      - name: Show OpenCL info
        run: clinfo --human
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
